### ISSUE TITLE
Autostarting

### ISSUE THREAD

**Issue by ghost** [netfri25/safwm#1]
it would be really awesome! btw does safwm support polybar? i saw in to do in config files but i also seen polynar_disable and enable variabls so yea

**Comment by netfri25** [comment]
wdym by autostart? like a shell script that runs on startup?
also yes, it "supports" polybar (which is the bar that I'm currently using) and today I also added more sensible support.
it's not really official support, just simple padding to maximized windows

**Comment by ghost** [comment]
@netfri25 this is what I meant https://github.com/dylanaraps/sowm/pull/106

**Comment by netfri25** [comment]
I think I can do that, but instead of `~/.sowm` I will rename it to `~/.safwm`

**Comment by ghost** [comment]
@netfri25 that will be really enough

**Comment by netfri25** [comment]
Done :grin:, you can try it out now

**Comment by ghost** [comment]
@netfri25 work as expected thank you!
