### ISSUE TITLE
Keyboard move and resize

### ISSUE THREAD

**Issue by ghost** [netfri25/safwm#2]
sowm has the patch, it would be really good if you could implement to safwm

**Comment by netfri25** [comment]
I do have keyboard resizing (with `mod` + `h`/`j`/`k`/`l`), and I will try to look at sowm implementation of moving windows with the keyboard

**Comment by netfri25** [comment]
Done :grin:, you can now use `mod` + `shift` + `h`/`j`/`k`/`l` to move windows (and ofc you can customize it to your liking).
Thanks for the suggestion! I really appreciate your feedback :smile:

**Comment by toprak** [comment]
Thank you!

**Comment by ghost** [comment]
@netfri25 you have resizing for shrinking though as far as I can understand there is no way to make it grow

**Comment by netfri25** [comment]
@toprak I thought about implementing it, but currently it doesn't really bother me.
I might do it in the near future, but for now you can either maximize the window and shrink it again (which is my preferred option) or just resize with the mouse.
it's already late and I have school tomorrow so I might implement it after school if I will have the time to do so

**Comment by ghost** [comment]
okay thanks

**Comment by netfri25** [comment]
Done :grin:, you can try it out now!
(btw I changed the keybindings for moving the windows to make extending/shrinking more sensible)

**Comment by ghost** [comment]
its really good! thank you!
